config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'calculator#index'
  get '/calculator/concat_text', to: 'calculator#concat_text', as: 'concat_text_calculator'
  get '/calculator/reset_text', to: 'calculator#reset_text', as: 'reset_text_calculator'
  get '/calculator/operation', to: 'calculator#operation', as: 'operation_calculator'
  get '/calculator/equals', to: 'calculator#equals', as: 'equals_calculator'
  get '/calculator', to: 'calculator#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculator_controller.rb
include ActionView::Helpers::NumberHelper

class CalculatorController < ApplicationController
    before_action :initialize_display_number

    def index
        reset_text
    end

    def concat_text
        # Recebe o texto como parâmetro
        text = params[:text]
    
        # Concatena o texto com a variável
        @displayNumber ||= ''
        @displayNumber += text
        session[:displayNumber] = @displayNumber  # Armazena em sessão

        render :index
    end

    def operation
        # Recebe o texto como parâmetro
        operation = params[:operation]

        if !@displayNumber.nil? && !@displayNumber.empty?
            @numberOperation = @displayNumber.empty? ? 0.0 : @displayNumber.to_f

            if @last_operation.nil? || @last_operation.empty?
                if (@result == 0.0)
                    @result = @numberOperation
                end
                refreshScreen()
            else     
                calculate()
            end
        end        

        @last_operation = operation
        session[:last_operation] = @last_operation     


        render :index
    end

    def equals
        @numberOperation = @displayNumber.empty? ? 0.0 : @displayNumber.to_f
        calculate()
        @last_operation = ''
        session[:last_operation] = ''
        render :index
    end    

    def calculate

        case @last_operation
        when "+"
          @result = @result + @numberOperation
        when "-"
            @result = @result - @numberOperation
        when "*"
            @result = @result * @numberOperation
        when "/"
            if (@numberOperation > 0)
                @result = @result / @numberOperation
            end                
        end

        refreshScreen()
    end    

    def refreshScreen
        session[:result] = @result

        @displayNumber = ''
        session[:displayNumber] = ''

        @formatted_result = number_with_precision(@result, precision: 2, separator: ',', delimiter: '.')
        session[:formatted_result] = @formatted_result
    end    
   
    def reset_text
        @displayNumber = ''
        session[:displayNumber] = ''
        @result = 0.0
        session[:result] = 0.0 
        @formatted_result = ''
        session[:formatted_result] = ''
        @last_operation = ''
        session[:last_operation] = ''
        render :index
    end 

    def initialize_display_number
        @displayNumber = session[:displayNumber] || ''
        @result = session[:result] || 0.0
        @formatted_result = session[:formatted_result] || ''
        @last_operation = session[:last_operation] || ''
    end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/views/calculator/index.html.erb
  <div class="calculator">
        <div class="result-calculator"><%= @formatted_result %></div>
        <input type="text" id="result" value="<%= @displayNumber %>"  readonly>
        <div class="calculator-buttons">
            <%= link_to concat_text_calculator_path(text: "7") do %>
                <button>7</button>
            <% end %>
            <%= link_to concat_text_calculator_path(text: "8") do %>
                <button>8</button>
            <% end %>
            <%= link_to concat_text_calculator_path(text: "9") do %>
                <button>9</button>
            <% end %>
            <%= link_to operation_calculator_path(operation: "+") do %>
                <button>+</button>
            <% end %>
            <%= link_to concat_text_calculator_path(text: "4") do %>
                <button>4</button>
            <% end %>
            <%= link_to concat_text_calculator_path(text: "5") do %>
                <button>5</button>
            <% end %>
            <%= link_to concat_text_calculator_path(text: "6") do %>
                <button>6</button>
            <% end %>
            <%= link_to operation_calculator_path(operation: "-") do %>
                <button>-</button>
            <% end %>
            <%= link_to concat_text_calculator_path(text: "1") do %>
                <button>1</button>
            <% end %>
            <%= link_to concat_text_calculator_path(text: "2") do %>
                <button>2</button>
            <% end %>
            <%= link_to concat_text_calculator_path(text: "3") do %>
                <button>3</button>
            <% end %>
            <%= link_to operation_calculator_path(operation: "*") do %>
                <button>*</button>
            <% end %>
            <%= link_to concat_text_calculator_path(text: "0") do %>
                <button>0</button>
            <% end %>
            <%= link_to concat_text_calculator_path(text: ".") do %>
                <button>.</button>
            <% end %>
            <%= link_to equals_calculator_path do %>
                <button>=</button>
            <% end %>
            <%= link_to operation_calculator_path(operation: "/") do %>
                <button>/</button>
            <% end %>
        </div>
        <%= link_to reset_text_calculator_path do %>
                 <button class="reset">Resetar</button>
            <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calculadora</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>